### ISSUE TITLE
Kdenlive crashes if typwriter is applied to a non video clip

### ISSUE THREAD

**Issue by smartfuturecode** [rlalik/mlt_extra_modules#4]
The Typwriter effect works (of course!) only on title clips, but if you drag it to a video clip in kdenlive (and maybe also other non tile clips) the app gets corrupt and freezes. I think this should not happen as it can happen accidentally or if a user don’t know how to use the effect.

**Comment by rlalik** [comment]
The effect was entering in infinite loop if no kdenlivetitler producer was found. It is fixed, please test.

**Comment by smartfuturecode** [comment]
Yes, seems fixed! Closing.
