### ISSUE TITLE
Kdenlive crashes if typwriter is applied to a template title

### ISSUE THREAD

**Issue by smartfuturecode** [rlalik/mlt_extra_modules#6]
**How to reproduce**

1. "Add template title" to project bin (no matter if it's a default one or a custom)
2. Drag it to the timeline
3. Apply typewriter effect
4. (hit play on timeline monitor)
5. Crash!

**Kdenlive log**
```
qml: [kdenlive/effect]
qml: Add effect:  typewriter
Asset  "typewriter"  found in the repository. Description:  "Typewriter effect v0.3.2 (typewriter)"
XML parsing of  "typewriter" . found 4 parameters
WARNING: Unknown type : "int"
WARNING: Unknown type : "int"
QLocale: Default value is QVariant(double, 25) parsed: "25"
 = = SET EFFECT PARAM:  "step_length"  =  25
WARNING: Unknown type : "int"
WARNING: Unknown type : "int"
QLocale: Default value is QVariant(double, 0) parsed: "0"
 = = SET EFFECT PARAM:  "step_sigma"  =  0
WARNING: Unknown type : "int"
WARNING: Unknown type : "int"
QLocale: Default value is QVariant(double, 0) parsed: "0"
 = = SET EFFECT PARAM:  "random_seed"  =  0
QLocale: Default value is QVariant(double, 1) parsed: "1"
 = = SET EFFECT PARAM:  "macro_type"  =  1
END parsing of  "typewriter" . Number of found parameters 4
// GOT CLIP STACK DATA CHANGE:  QVector(305)
// GOT CLIP STACK DATA CHANGE DONE:  QModelIndex(0,0,0x6,TimelineItemModel(0x55f355caae70))  =  QVector(305)
Segmentation fault (core dumped)
```

**Comment by rlalik** [comment]
OK, I managed to fix the problem in mlt side. But still there is problem in kdenlive:
1. If in project bin you choose: Add Template Title, and you apply the effect, it won't do anything
2. If you Add Title Clip, and then in the Title Clip Edit Widget you select template (in the bottom) and update the clip, it will do.
3. If you edit the clip taken in point 1, and update it, it will do.

I have to see more what happens in case 1.

**Comment by smartfuturecode** [comment]
Yes, to me it also only happened on newly imported template title, if I changed it before it everything worked fine.

**Comment by smartfuturecode** [comment]
Seems fixed. Closing.
