### ISSUE TITLE
"By Char" mode error in multibyte languages

### ISSUE THREAD

**Issue by alogblog** [rlalik/mlt_extra_modules#7]
Hi
First of all, I'd like to thank you for developing this wonderful effect.

I'm Korean, so I use Korean language :)
Korean or most of Asian uses multibye or 2 bytes languages or Unicode?

I saw this Typewriter module process unicode in character processing.
But anyway I think its not perfect, because when I use "by char" expansion mode in Kdenlive, each Korean character is shown as "�" temporarily.

You might reproduce this error by using "mdash(—)" character in texts.

> The replacement character � (often displayed as a black rhombus with a white question mark) is a symbol found in the Unicode standard at code point U+FFFD in the Specials table. It is used to indicate problems when a system is unable to render a stream of data to a correct symbol.

So in code, I think, when  "by char"ed character is U+FFFD, then final resulting char can be replaced with normal space(" ").

![screen03](https://user-images.githubusercontent.com/584593/137047453-3c7fef3e-cc70-4da8-be26-33346a30ebcc.png)
![screen04 png](https://user-images.githubusercontent.com/584593/137047461-854b0781-7230-4118-9d18-bb4f79bcf722.jpg)

I found this video in youtube.
https://youtu.be/SWxTHxUYyLY

**Comment by rlalik** [comment]
Hi, thank you for reporting this.

This problem was already reported once some couple months ago already, but unfortunately I was short of time for working on it. In the next couple of days I will try to put hands on it and fix it.

In the meantime, can you past here some example strings which causes the problem that I can verify the fix, or share the whole kdenlive project with MWE?

**Comment by alogblog** [comment]
반갑습니다! (Nice to meet you!)

I browsed source code typewriter.cpp.
In function detectUtf8(),

From
static const unsigned char masks[5] = { 0xfc, 0xf8, 0xf0, 0xc0, 0x80 };
To
static const unsigned char masks[5] = { 0xfc, 0xf8, 0xf0, **0xe0**, 0xc0, 0x80 }; ???

In that case, some characters with 2~3 bytes might be wrongly processed, although I'm not sure.

**Comment by rlalik** [comment]
You are right, I missed it, but anyway even without it, I rewrote the function in much simpler way without using masks, so I fixed this error accidentally. In fact the change should be:

    0xc0 -> 0xe8
    0x80 -> 0xc0

as 0x80 is not valid UTF-8 pattern. After finishing the test, I will push fix to mlt.

Please note that many months ago this effect was merged into mlt so you do not need to install `mlt_extra_modules` separately. I will add deprecation notice to the README.

**Comment by rlalik** [comment]
The fix was push requested to mlt: https://github.com/mltframework/mlt/pull/739

I think with this we can close this issue.
